name: Release

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  github-release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: "Get version"
        id: get-version
        run: |
          echo "new_version=$(cat VERSION)" >> ${GITHUB_OUTPUT}
      - name: "Create release"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.new_version }}
          release_name: Release ${{ steps.get-version.outputs.new_version }}
          draft: false
      - name: "Override latest"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete latest --cleanup-tag --yes --repo ${{ github.repository }} || true
      - name: "Create release"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "latest"
          release_name: "Release latest"
          draft: false

